(defun re-format (MARK DOT size)
    "reformatting text file like fold(1) but this function 
recognize word"
    (interactive "r
ntext size: ")
    (save-window-excursion
	(save-restriction
	    (narrow-to-region MARK DOT)
	    (beginning-of-buffer)
	    (while (not (eobp))
		(progn ()
		    (while (> (progn ()
				(end-of-line)
				(current-column)) size)
			(progn ()
			    (beginning-of-line)
			    (forward-char size)
			    (backward-word 2)
			    (forward-word 1)
			    (insert-string "\n")
			)
		    )
		    (end-of-line)
		    (backward-char 1)
		    (if (and (not (looking-at ".")) (not (looking-at "!"))
			    (not (looking-at "?")))
			(progn ()
			    (end-of-line)
			    (delete-char 1)
			)
			(progn ()
			    (next-line 1)
			    (beginning-of-line)
			)
		    )
		)
	    )
	)
    )
)

